"""
Deploy pipeline functions.

Handles config generation, systemd service creation, and full deploy-to-board workflow.
"""

import os
import time
import tempfile
import subprocess
from typing import Dict, Any

from mcp_build.config import resolve_config, get_binary_path, ssh_execute
from mcp_build.build import build_toolkit, build_target


def generate_config_yaml(platform: str, model_path: str) -> str:
    """Generate a YAML config file content for the given platform"""
    if platform == "rock3c":
        return f"""# AI Camera Trap Configuration - ROCK 3C (RK3566)
# Auto-generated by ai-trap-build deploy tool

camera:
  model: "imx219"
  full_w: 1920
  full_h: 1080
  med_w: 640
  med_h: 480
  lores_w: 320
  lores_h: 320
  fps: 15
  device: "/dev/video0"
  scene_dir: ""
  iq_dir: "/usr/share/iqfiles"

inference:
  backend: "rknn"
  model_path: "{model_path}"
  confidence_threshold: 0.5

storage:
  output_dir: "/var/lib/ai-trap/detections"
  db_path: "/var/lib/ai-trap/trap.db"

cropper:
  padding_px: 10
  min_confidence: 0.5

classifier:
  model_path: ""
  confidence_threshold: 0.5
  input_width: 224
  input_height: 224

actuator:
  type: "none"
  gpio: -1
  duration_ms: 3000

motion_sensor:
  gpio: -1

decision:
  trigger_confidence: 0.6
  cooldown_ms: 3000
"""
    elif platform == "cubie-a7s":
        return f"""# AI Camera Trap Configuration - Cubie A7S (Allwinner A527)
# Auto-generated by ai-trap-build deploy tool

camera:
  model: "a7s"
  full_w: 1920
  full_h: 1080
  med_w: 640
  med_h: 480
  lores_w: 320
  lores_h: 320
  fps: 15
  device: "/dev/video0"
  scene_dir: ""
  iq_dir: "/usr/share/iqfiles"

inference:
  backend: "bpu"
  model_path: "{model_path}"
  confidence_threshold: 0.5

storage:
  output_dir: "/var/lib/ai-trap/detections"
  db_path: "/var/lib/ai-trap/trap.db"

cropper:
  padding_px: 10
  min_confidence: 0.5

classifier:
  model_path: ""
  confidence_threshold: 0.5
  input_width: 224
  input_height: 224

actuator:
  type: "none"
  gpio: -1
  duration_ms: 3000

motion_sensor:
  gpio: -1

decision:
  trigger_confidence: 0.6
  cooldown_ms: 3000
"""
    else:
        return f"""# AI Camera Trap Configuration - {platform}
# Auto-generated by ai-trap-build deploy tool

camera:
  model: "generic"
  full_w: 1920
  full_h: 1080
  med_w: 640
  med_h: 480
  lores_w: 320
  lores_h: 320
  fps: 15
  device: "/dev/video0"
  scene_dir: ""
  iq_dir: ""

inference:
  backend: "auto"
  model_path: "{model_path}"
  confidence_threshold: 0.5

storage:
  output_dir: "/var/lib/ai-trap/detections"
  db_path: "/var/lib/ai-trap/trap.db"

cropper:
  padding_px: 10
  min_confidence: 0.5

classifier:
  model_path: ""
  confidence_threshold: 0.5
  input_width: 224
  input_height: 224

actuator:
  type: "none"
  gpio: -1
  duration_ms: 3000

motion_sensor:
  gpio: -1

decision:
  trigger_confidence: 0.6
  cooldown_ms: 3000
"""


def generate_systemd_service(trap_name: str, binary_path: str, config_path: str) -> str:
    """Generate a systemd service unit file content"""
    return f"""[Unit]
Description=AI Camera Trap Detection Service ({trap_name})
After=network.target

[Service]
Type=simple
ExecStart={binary_path} --config {config_path}
Restart=on-failure
RestartSec=5
User=root

[Install]
WantedBy=multi-user.target
"""


def deploy_to_board(platform: str, params: Dict[str, Any]) -> Dict[str, Any]:
    """Full deploy pipeline: build -> install -> deploy model/config -> create service -> start"""
    cfg = resolve_config(platform, params)
    if "error" in cfg:
        return cfg

    host = cfg["host"]
    user = cfg["user"]
    build_dir = cfg["build_dir"]
    remote_dir = cfg["remote_dir"]
    project_root = cfg["project_root"]
    trap_name = cfg["trap_name"]
    install_path = params.get("install_path", "/usr/local/bin")
    start_service = params.get("start", True)
    rebuild = params.get("rebuild", False)

    model_type = cfg.get("model_type")
    model_install_dir = "/usr/share/ai-trap/models"
    model_install_path = f"{model_install_dir}/yolo11n.{model_type}" if model_type else None

    config_install_dir = "/etc/ai-trap"
    config_install_path = f"{config_install_dir}/config.yaml"

    binary_build_path = get_binary_path(remote_dir, build_dir, cfg["trap_path_template"], trap_name)
    binary_install_path = f"{install_path}/{trap_name}"

    steps = []

    # Step 1: Build toolkit
    steps.append({"step": 1, "name": "Build toolkit", "status": "pending"})
    toolkit_result = build_toolkit(platform, params)
    if not toolkit_result.get("success", False):
        return {
            "success": False,
            "message": f"Deploy failed at Step 1 (toolkit build): {toolkit_result.get('message', 'unknown error')}",
            "steps": steps + [{"step": 1, "name": "Build toolkit", "status": "failed", "detail": toolkit_result.get('message')}]
        }
    steps[-1]["status"] = "completed"

    # Step 2: Build target
    steps.append({"step": 2, "name": "Build target", "status": "pending"})
    target_result = build_target(platform, params)
    if not target_result.get("success", False):
        return {
            "success": False,
            "message": f"Deploy failed at Step 2 (target build): {target_result.get('message', 'unknown error')}",
            "steps": steps + [{"step": 2, "name": "Build target", "status": "failed", "detail": target_result.get('message')}]
        }
    steps[-1]["status"] = "completed"

    # Step 3: Install binary
    steps.append({"step": 3, "name": "Install binary", "status": "pending"})
    install_cmd = (
        f"sudo mkdir -p {install_path} && "
        f"sudo cp {binary_build_path} {binary_install_path} && "
        f"sudo chmod +x {binary_install_path} && "
        f"sudo chown root:root {binary_install_path}"
    )
    install_result = ssh_execute(user, host, install_cmd, timeout=30)
    if not install_result["success"]:
        return {
            "success": False,
            "message": f"Deploy failed at Step 3 (install binary): {install_result['combined'][-500:]}",
            "steps": steps + [{"step": 3, "name": "Install binary", "status": "failed", "detail": install_result['combined'][-500:]}]
        }
    steps[-1]["status"] = "completed"
    steps[-1]["binary_path"] = binary_install_path

    # Step 4: Deploy model file
    steps.append({"step": 4, "name": "Deploy model", "status": "pending"})
    model_path_param = params.get("model_path")
    if model_path_param and os.path.isfile(model_path_param):
        ssh_execute(user, host, f"sudo mkdir -p {model_install_dir}", timeout=10)
        scp_cmd = ["scp", model_path_param, f"{user}@{host}:/tmp/deploy_model"]
        try:
            subprocess.run(scp_cmd, capture_output=True, text=True, timeout=60)
            move_cmd = f"sudo mv /tmp/deploy_model {model_install_path} && sudo chmod 644 {model_install_path}"
            mv_result = ssh_execute(user, host, move_cmd, timeout=15)
            if mv_result["success"]:
                steps[-1]["status"] = "completed"
                steps[-1]["model_path"] = model_install_path
            else:
                steps[-1]["status"] = "skipped"
                steps[-1]["detail"] = f"Failed to install model: {mv_result['combined'][-200:]}"
        except Exception as e:
            steps[-1]["status"] = "skipped"
            steps[-1]["detail"] = f"Failed to copy model: {str(e)}"
    else:
        check_cmd = f"test -f {model_install_path} && echo 'exists' || echo 'missing'"
        check_result = ssh_execute(user, host, check_cmd, timeout=10)
        if check_result["stdout"].strip() == "exists":
            steps[-1]["status"] = "skipped"
            steps[-1]["detail"] = f"Model already exists at {model_install_path}"
        else:
            steps[-1]["status"] = "skipped"
            steps[-1]["detail"] = f"No model provided and none found at {model_install_path}. Deploy model separately."

    # Step 5: Deploy config file
    steps.append({"step": 5, "name": "Deploy config", "status": "pending"})
    config_path_param = params.get("config_path")
    if config_path_param and os.path.isfile(config_path_param):
        ssh_execute(user, host, f"sudo mkdir -p {config_install_dir}", timeout=10)
        scp_cmd = ["scp", config_path_param, f"{user}@{host}:/tmp/deploy_config.yaml"]
        try:
            subprocess.run(scp_cmd, capture_output=True, text=True, timeout=30)
            move_cmd = f"sudo mv /tmp/deploy_config.yaml {config_install_path} && sudo chmod 644 {config_install_path}"
            mv_result = ssh_execute(user, host, move_cmd, timeout=15)
            if mv_result["success"]:
                steps[-1]["status"] = "completed"
                steps[-1]["config_path"] = config_install_path
            else:
                steps[-1]["status"] = "failed"
                steps[-1]["detail"] = f"Failed to install config: {mv_result['combined'][-200:]}"
                return {"success": False, "message": "Deploy failed at Step 5 (deploy config)", "steps": steps}
        except Exception as e:
            steps[-1]["status"] = "failed"
            steps[-1]["detail"] = f"Failed to copy config: {str(e)}"
            return {"success": False, "message": "Deploy failed at Step 5 (deploy config)", "steps": steps}
    else:
        model_for_config = model_install_path or "/usr/share/ai-trap/models/yolo11n.rknn"
        config_yaml = generate_config_yaml(platform, model_for_config)
        with tempfile.NamedTemporaryFile(mode='w', suffix='.yaml', delete=False) as f:
            f.write(config_yaml)
            tmp_path = f.name
        try:
            ssh_execute(user, host, f"sudo mkdir -p {config_install_dir}", timeout=10)
            scp_cmd = ["scp", tmp_path, f"{user}@{host}:/tmp/deploy_config.yaml"]
            subprocess.run(scp_cmd, capture_output=True, text=True, timeout=30)
            move_cmd = f"sudo mv /tmp/deploy_config.yaml {config_install_path} && sudo chmod 644 {config_install_path}"
            mv_result = ssh_execute(user, host, move_cmd, timeout=15)
            if mv_result["success"]:
                steps[-1]["status"] = "completed"
                steps[-1]["config_path"] = config_install_path
            else:
                steps[-1]["status"] = "failed"
                steps[-1]["detail"] = f"Failed to install generated config: {mv_result['combined'][-200:]}"
                os.unlink(tmp_path)
                return {"success": False, "message": "Deploy failed at Step 5 (deploy config)", "steps": steps}
        except Exception as e:
            steps[-1]["status"] = "failed"
            steps[-1]["detail"] = f"Failed to deploy generated config: {str(e)}"
            os.unlink(tmp_path)
            return {"success": False, "message": "Deploy failed at Step 5 (deploy config)", "steps": steps}
        os.unlink(tmp_path)

    # Step 6: Create systemd service
    steps.append({"step": 6, "name": "Create systemd service", "status": "pending"})
    service_unit = generate_systemd_service(trap_name, binary_install_path, config_install_path)
    service_path = f"/etc/systemd/system/{trap_name}.service"
    with tempfile.NamedTemporaryFile(mode='w', suffix='.service', delete=False) as f:
        f.write(service_unit)
        tmp_service = f.name
    try:
        scp_cmd = ["scp", tmp_service, f"{user}@{host}:/tmp/{trap_name}.service"]
        subprocess.run(scp_cmd, capture_output=True, text=True, timeout=30)
        install_service_cmd = (
            f"sudo mv /tmp/{trap_name}.service {service_path} && "
            f"sudo chmod 644 {service_path} && "
            f"sudo systemctl daemon-reload && "
            f"sudo systemctl enable {trap_name}.service"
        )
        svc_result = ssh_execute(user, host, install_service_cmd, timeout=30)
        if svc_result["success"]:
            steps[-1]["status"] = "completed"
            steps[-1]["service_path"] = service_path
        else:
            steps[-1]["status"] = "failed"
            steps[-1]["detail"] = f"Failed to install/enable service: {svc_result['combined'][-500:]}"
            os.unlink(tmp_service)
            return {"success": False, "message": "Deploy failed at Step 6 (systemd service)", "steps": steps}
    except Exception as e:
        steps[-1]["status"] = "failed"
        steps[-1]["detail"] = f"Failed to create service: {str(e)}"
        os.unlink(tmp_service)
        return {"success": False, "message": "Deploy failed at Step 6 (systemd service)", "steps": steps}
    os.unlink(tmp_service)

    # Step 7: Start and verify
    steps.append({"step": 7, "name": "Start service", "status": "pending"})
    if start_service:
        start_cmd = f"sudo systemctl start {trap_name}.service"
        start_result = ssh_execute(user, host, start_cmd, timeout=30)
        if start_result["success"]:
            time.sleep(2)
            status_cmd = f"sudo systemctl status {trap_name}.service --no-pager 2>&1"
            status_result = ssh_execute(user, host, status_cmd, timeout=15)
            steps[-1]["status"] = "completed"
            steps[-1]["service_status"] = status_result["stdout"][:1000]

            verify_cmd = "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/status 2>/dev/null || echo 'unreachable'"
            verify_result = ssh_execute(user, host, verify_cmd, timeout=10)
            if verify_result["stdout"].strip() == "200":
                steps[-1]["api_status"] = "online (HTTP 200)"
            else:
                steps[-1]["api_status"] = f"checking... (response: {verify_result['stdout'].strip()})"
        else:
            steps[-1]["status"] = "failed"
            steps[-1]["detail"] = f"Failed to start service: {start_result['combined'][-500:]}"
            return {"success": False, "message": "Deploy failed at Step 7 (start service)", "steps": steps}
    else:
        steps[-1]["status"] = "skipped"
        steps[-1]["detail"] = "Service not started (start=false)"

    return {
        "success": True,
        "message": f"Deploy completed successfully for {platform}/{trap_name}",
        "binary": binary_install_path,
        "config": config_install_path,
        "service": f"{trap_name}.service",
        "steps": steps
    }
